name: sondreb/action-release
description: |
  GitHub Release Action
author: Sondre Bjellås
branding:
  icon: box
  color: gray-dark
inputs:
  token:
    description: 'The GitHub token.'
    required: true
    default: ''
  tag:
    description: 'An optional tag for the release. If this is omitted the git ref will be used (if it is a tag).'
    default: ''
  name:
    required: true
  draft:
    description: "Optionally marks this release as a draft release. Set to true to enable."
    default: false
  prerelease:
    default: false
  files:
    required: false
    default: ''
  folder:
    required: false
    default: ''
  commit:
    required: false
    default: 'main'
  body:
    default: ''
  verbose:
    required: false
    default: 'false'
runs:
  using: node16
  main: action.js